// <auto-generated />
using System;
using Gurusoft.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gurusoft.Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240628154551_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gurusoft.Domain.NumeroPrimo", b =>
                {
                    b.Property<int>("IdNumeroPrimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumeroPrimo"));

                    b.Property<DateTime>("FechaRequest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaResponse")
                        .HasColumnType("datetime2");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdNumeroPrimo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NumeroPrimo");
                });

            modelBuilder.Entity("Gurusoft.Domain.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Gurusoft.Domain.NumeroPrimo", b =>
                {
                    b.HasOne("Gurusoft.Domain.Usuario", "Usuario")
                        .WithMany("NumeroPrimo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gurusoft.Domain.Usuario", b =>
                {
                    b.Navigation("NumeroPrimo");
                });
#pragma warning restore 612, 618
        }
    }
}
